// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alptwtejhkjnaxgmbeie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFscHR3dGVqaGtqbmF4Z21iZWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjM3MjgsImV4cCI6MjA2MDAzOTcyOH0.tPKStW9kWr1dtJ198-dyKcghs8otq4TR_Z-u_2vuOlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);